//Nome: Leonardo Canuto Junior -  RA: 2453533
package com.mycompany.lista5;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author leona
 */
public class RelatGeral extends javax.swing.JFrame {

    /**
     * Creates new form RelatGeral
     */
    static RelatGeral relatGeral_unico;
    
    private RelatGeral() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public static RelatGeral getRelatGeral(){
        if(relatGeral_unico == null)
            relatGeral_unico = new RelatGeral();
        return relatGeral_unico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        scRelatGeral = new javax.swing.JScrollPane();
        tbRelatGeral = new javax.swing.JTable();
        lbFiltrar = new javax.swing.JLabel();
        cbPasseio = new javax.swing.JCheckBox();
        cbCarga = new javax.swing.JCheckBox();
        btAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        lbTitulo.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Banco de veículos");
        lbTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbTitulo.setMaximumSize(new java.awt.Dimension(112, 16));

        tbRelatGeral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Última alteração", "Placa", "Marca", "Modelo", "Cor", "Tipo do veículo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbRelatGeral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbRelatGeralMouseClicked(evt);
            }
        });
        scRelatGeral.setViewportView(tbRelatGeral);
        if (tbRelatGeral.getColumnModel().getColumnCount() > 0) {
            tbRelatGeral.getColumnModel().getColumn(0).setResizable(false);
            tbRelatGeral.getColumnModel().getColumn(1).setResizable(false);
            tbRelatGeral.getColumnModel().getColumn(2).setResizable(false);
            tbRelatGeral.getColumnModel().getColumn(3).setResizable(false);
            tbRelatGeral.getColumnModel().getColumn(4).setResizable(false);
            tbRelatGeral.getColumnModel().getColumn(5).setResizable(false);
        }

        lbFiltrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbFiltrar.setText("Filtrar por");

        cbPasseio.setSelected(true);
        cbPasseio.setText("Veículos de passeio");

        cbCarga.setSelected(true);
        cbCarga.setText("Veículos de carga");

        btAtualizar.setText("Atualizar");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scRelatGeral, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbFiltrar)
                        .addGap(18, 18, 18)
                        .addComponent(cbPasseio)
                        .addGap(18, 18, 18)
                        .addComponent(cbCarga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btAtualizar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFiltrar)
                    .addComponent(cbPasseio)
                    .addComponent(cbCarga)
                    .addComponent(btAtualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scRelatGeral, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        listarTab();
    }//GEN-LAST:event_formWindowActivated

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        listarTab();
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void tbRelatGeralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbRelatGeralMouseClicked
        selecTab();
    }//GEN-LAST:event_tbRelatGeralMouseClicked

    /**
     * @param args the command line arguments
     */
    public void listarTab(){
        DefaultTableModel tabModel = (DefaultTableModel) tbRelatGeral.getModel();
        int posLin = 0;
        tabModel.setRowCount(posLin);
        
        if(cbPasseio.isSelected()){
            for(Passeio p : BancoVeic.getBancoVeic().getBdPasseio()){
                tabModel.insertRow(posLin, new Object[]{p.getDataCadastro(),p.getPlaca(),p.getModelo(),p.getModelo(),p.getCor(),"Passeio"});
                posLin++;
            }
        }
        if(cbCarga.isSelected()){
            for(Carga c : BancoVeic.getBancoVeic().getBdCarga()){
                tabModel.insertRow(posLin, new Object[]{c.getDataCadastro(),c.getPlaca(),c.getModelo(),c.getModelo(),c.getCor(),"Carga"});
                posLin++;
            }
        }
    }
    public void selecTab(){
        String txtLin = "";
        
        int posLin = tbRelatGeral.getSelectedRow();
        if(tbRelatGeral.getModel().getValueAt(posLin, 5).toString().equals("Passeio")){
            Passeio p = new Passeio();
            p.setPlaca(tbRelatGeral.getModel().getValueAt(posLin, 1).toString());
        }else{
            Carga c = new Carga();
            c.setPlaca(tbRelatGeral.getModel().getValueAt(posLin, 1).toString());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JCheckBox cbCarga;
    private javax.swing.JCheckBox cbPasseio;
    private javax.swing.JLabel lbFiltrar;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JScrollPane scRelatGeral;
    private javax.swing.JTable tbRelatGeral;
    // End of variables declaration//GEN-END:variables
}
